export enum ActionTypes {
    FETCHUSERS = "FETCHUSERS",
    SUCCESSFETCHUSERS = "SUCCESSFETCHUSERS",
    FAILUREFETCHUSERS = "FAILUREFETCHUSERS",
    DELETEUSERS = "DELETEUSERS",
    SUCCESSDELETEUSERS = "SUCCESSDELETEUSERS",
    FAILUREDELETEUSERS = "FAILUREDELETEUSERS",
    CREATEUSER = "CREATEUSER",
    SUCCESSCREATEUSER = "SUCCESSCREATEUSER",
    FAILURECREATEUSER = "FAILURECREATEUSER",
    CONFIRMUSER = "CONFIRMUSER",
    SUCCESSCONFIRMUSER = "SUCCESSCONFIRMUSER",
    FAILEDCONFIRMUSER = "FAILEDCONFIRMUSER",
    FETCHPOST = "FETCHPOST",
    SUCCESSFETCHPOST = "SUCCESSFETCHPOST",
    FAILUREFETCHPOST = "FAILUREFETCHPOST",
    UPLOADPOST = "UPLOADPOST",
    SUCCESSUPLOADPOST = "SUCCESSUPLOADPOST",
    FAILUREUPLOADPOST = "FAILUREUPLOADPOST",
    DELETEPOST = "DELETEPOST",
    SUCCESSDELETEPOST = "SUCCESSDELETEPOST",
    FAILUREDELETEPOST = "FAILUREDELETEPOST"

}